### ISSUE TITLE
Sphinx 2.0+ incompatibility: 'Sphinx' object has no attribute 'warn

### ISSUE THREAD

**Issue by bsipocz** [astropy/sphinx-automodapi#80]
We seem to have a few untested instances that breaks with sphinx 2.0+. Everything still works well with Sphinx 1.8.5
```
Exception occurred:
  File "/usr/local/lib/python3.7/site-packages/sphinx_automodapi/automodapi.py", line 285, in automodapi_replace
    app.warn(msg, location)
AttributeError: 'Sphinx' object has no attribute 'warn'
The full traceback has been saved in /var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/sphinx-err-v4w2tac0.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Sphinx Documentation subprocess failed with return code 2
```

**Comment by rishabkhincha** [comment]
I'm facing the exact same issue as well!

**Comment by rishabkhincha** [comment]
@astrofrog

**Comment by astrofrog** [comment]
I'm working on this

**Comment by peterjc** [comment]
Is a release with this fix pending?

**Comment by bsipocz** [comment]
Yes it's correct, no release has been cut yet with this fix.

**Comment by astrofrog** [comment]
@peterjc @bsipocz sphinx-automodapi v0.12 is now released: https://pypi.org/project/sphinx-automodapi/0.12/
